### ISSUE TITLE
Displaying output from opencv to a canvas in python tkinter

### ISSUE THREAD

**Issue by Dev-Akash** [Dev-Akash/Chromatica#1]
Right now the output is shown as a frame created by opencv, we have to change that to a custom window with having more valuable options used for editing videos on chroma. That's why we have to display the frame captured by camera to a canvas in tkinter.

**Comment by ShantanuShinde** [comment]
what should I do regarding the closing? In tkinter the video will stop with button, so, should add button to break the loop, or just replace the display of frame with tkinter

**Comment by Dev-Akash** [comment]
@ShantanuShinde Just go with relpacing the display of frame with tkinter.

**Comment by ShantanuShinde** [comment]
> @ShantanuShinde Just go with relpacing the display of frame with tkinter.

where are the images? the images in the array are not in the repo

**Comment by Dev-Akash** [comment]
@ShantanuShinde its about showing or displaying the video feed output from opencv to canvas of tkinter. I hope you got it right ..?

**Comment by ShantanuShinde** [comment]
> @ShantanuShinde its about showing or displaying the video feed output from opencv to canvas of tkinter. I hope you got it right ..?

yes, I got that. I just asked because the cv2 gives error as the files dont exists. I commented out the images code, so now its not giving the error

**Comment by ShantanuShinde** [comment]
Is the PR good?
